baseURL = 'https://gopancakes.de/'
languageCode = 'en-us'
title = 'Go Pancakes'
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3
enableRobotsTXT = true

[languages]
    [languages.en]
    title = "Go Pancakes"
    weight = 1
    contentDir = "content/en"

[params]
description = "Bucket List in the search for the dreamy pancakes 🥞"
background_color_class = "bg-dark-blue"
recent_posts_number = 3